
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SIGNO_MENOS = 4;
  public static final int IDD = 8;
  public static final int FIN = 3;
  public static final int ESCRIBIR = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SIGNO_DIVISION = 6;
  public static final int SIGNO_POR = 5;
  public static final int SIGNO_MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESCRIBIR",
  "FIN",
  "SIGNO_MENOS",
  "SIGNO_POR",
  "SIGNO_DIVISION",
  "SIGNO_MAS",
  "IDD"
  };
}

